-- 코드를 입력하세요

SELECT ROUND(AVG(DAILY_FEE)) AS 'AVERAGE_FEE'
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE='SUV';


/*
SELECT SUM(DAILY_FEE) AS 'sum', COUNT(CAR_TYPE) AS 'count'
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE='SUV';
*/

