SELECT *
FROM (
    SELECT 
        LEFT(SALES_DATE, 10) AS 'SALES_DATE', PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE as on_t
    WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

    UNION ALL

    SELECT 
        LEFT(SALES_DATE, 10) AS 'SALES_DATE', PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE as off_t
    WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
) AS t1
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC