-- 코드를 입력하세요
# SELECT CAR_ID, ROUND(AVG(DATEDIFF(START_DATE, END_DATE)), 2) as 'AVERAGE_DURATION'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# group by CAR_ID
# having AVERAGE_DURATION >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

# SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) as 'AVERAGE_DURATION'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# group by CAR_ID
# having AVERAGE_DURATION >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

select car_id, round(avg(datediff(end_date, start_date)+1), 1) as 'AVERAGE_DURATION'
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by car_id
having AVERAGE_DURATION >= 7
order by AVERAGE_DURATION desc, car_id desc
# 2, 0 , 10, 2, 4, 30, 93