-- 코드를 입력하세요
SELECT
    ugb.TITLE as 'TITLE', ugb.BOARD_ID as 'BOARD_ID', 
    ugr.REPLY_ID as 'REPLY_ID', ugr.WRITER_ID as 'WRITER_ID',
    ugr.CONTENTS as 'CONTENTS', LEFT(ugr.CREATED_DATE, 10) as 'CREATED_DATE'
FROM USED_GOODS_BOARD as ugb
    INNER JOIN USED_GOODS_REPLY as ugr on ugb.BOARD_ID = ugr.BOARD_ID
WHERE ugb.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE ASC;